app:
  mode: ${APP_MODE}
http_server:
  port: ${HTTP_SERVER_PORT}
grpc_server:
  port: ${GRPC_SERVER_PORT}
notification_event:
  username: ${KAFKA_USERNAME}
  password: ${KAFKA_PASSWORD}
  bootstrap_servers: ${KAFKA_BOOTSTRAP_SERVERS}
  ssl_root_ca_path: ${KAFKA_SSL_ROOT_CERT}
tg:
  bot:
    token: ${TG_BOT_TOKEN}
